Repository covid-projections/covid-data-model, pull requests merged in 2020-04, with the labels that each got.

#107 [EPIC] Add PySEIR Model
  .github/workflows/deploy_api.yml
  .gitignore
  README.md
  deploy_dod.sh
  deploy_website.sh
  environment.yaml
  libs/datasets/data_source.py
  libs/enums.py
  pyseir/__init__.py
  pyseir/cli.py
  pyseir/deployment/webui_data_adaptor_v1.py
  pyseir/ensembles/__init__.py
  pyseir/ensembles/ensemble_runner.py
  pyseir/inference/__init__.py
  pyseir/inference/fit_results.py
  pyseir/inference/infer_t0.py
  pyseir/inference/initial_conditions_fitter.py
  pyseir/inference/model_fitter.py
  pyseir/load_data.py
  pyseir/models/__init__.py
  pyseir/models/seir_model.py
  pyseir/models/suppression_policies.py
  pyseir/optimization/__init__.py
  pyseir/optimization/policy_optimizer.py
  pyseir/parameters/__init__.py
  pyseir/parameters/parameter_ensemble_generator.py
  pyseir/reports/__init__.py
  pyseir/reports/county_report.py
  pyseir/reports/names.py
  pyseir/reports/pdf_report.py
  pyseir/reports/state_report.py
  pyseir_data/.keep
  pyseir_data/county_metadata.json
  requirements.txt
  run.sh
  setup.py
Labels: DO NOT MERGE

#238 Rebase: model/add_priors
  pyseir/cli.py
  pyseir/deployment/webui_data_adaptor_v1.py
  pyseir/ensembles/ensemble_runner.py
  pyseir/inference/fit_results.py
  pyseir/inference/model_fitter.py
  pyseir/load_data.py
  pyseir/models/suppression_policies.py
  pyseir/utils.py
Labels: Modeling

#253 Model/add cumulative total infections and fix hosp data filter
  pyseir/inference/model_fitter.py
Labels: Modeling

#262 Fix random seed for inference.
  pyseir/inference/model_fitter.py
Labels: Modeling

#269 Add R_eff and error to the output webui data model
  pyseir/deployment/webui_data_adaptor_v1.py
Labels: Modeling

#270 Add County Inference [Not QAd]
  pyseir/ensembles/ensemble_runner.py
  pyseir/inference/model_fitter.py
  pyseir/models/seir_model.py
  pyseir/parameters/parameter_ensemble_generator.py
Labels: Modeling

#271 Model/add rt inference
  pyseir/cli.py
  pyseir/inference/infer_rt.py
  pyseir/inference/whitelist_generator.py
  pyseir/utils.py
Labels: Modeling

#280 Minor Bugfixes
  pyseir/cli.py
  pyseir/deployment/webui_data_adaptor_v1.py
  pyseir/inference/infer_rt.py
  pyseir/inference/model_fitter.py
Labels: Bug, Modeling

#282 Model/add whitelist for counties: Fix state level inference in whitelist.
  pyseir/deployment/webui_data_adaptor_v1.py
Labels: Bug, Modeling

#287 Expose ICU / Vent Compartments and Capacity Information
  libs/datasets/can_model_output_schema.py
  pyseir/deployment/webui_data_adaptor_v1.py
Labels: Modeling

#326 R_t Add KeyError handling
  pyseir/deployment/webui_data_adaptor_v1.py
Labels: Bug

#239 Rebase: model/add_pyseir_age_structure
  environment.yaml
  pyseir/inference/model_fitter.py
  pyseir/load_data.py
  pyseir/models/seir_model.py
  pyseir/models/seir_model_age.py
  pyseir/models/suppression_policies.py
  pyseir/parameters/parameter_ensemble_generator_age.py
  pyseir_data/cdc_hospitalization_data.csv
  pyseir_data/contact_matrix/contact_matrix_fips_AK.json
  pyseir_data/contact_matrix/contact_matrix_fips_AL.json
  pyseir_data/contact_matrix/contact_matrix_fips_AR.json
  pyseir_data/contact_matrix/contact_matrix_fips_AZ.json
  pyseir_data/contact_matrix/contact_matrix_fips_CA.json
  pyseir_data/contact_matrix/contact_matrix_fips_CO.json
  pyseir_data/contact_matrix/contact_matrix_fips_CT.json
  pyseir_data/contact_matrix/contact_matrix_fips_DC.json
  pyseir_data/contact_matrix/contact_matrix_fips_DE.json
  pyseir_data/contact_matrix/contact_matrix_fips_FL.json
  pyseir_data/contact_matrix/contact_matrix_fips_GA.json
  pyseir_data/contact_matrix/contact_matrix_fips_HI.json
  pyseir_data/contact_matrix/contact_matrix_fips_IA.json
  pyseir_data/contact_matrix/contact_matrix_fips_ID.json
  pyseir_data/contact_matrix/contact_matrix_fips_IL.json
  pyseir_data/contact_matrix/contact_matrix_fips_IN.json
  pyseir_data/contact_matrix/contact_matrix_fips_KS.json
  pyseir_data/contact_matrix/contact_matrix_fips_KY.json
  pyseir_data/contact_matrix/contact_matrix_fips_LA.json
  pyseir_data/contact_matrix/contact_matrix_fips_MA.json
  pyseir_data/contact_matrix/contact_matrix_fips_MD.json
  pyseir_data/contact_matrix/contact_matrix_fips_ME.json
  pyseir_data/contact_matrix/contact_matrix_fips_MI.json
  pyseir_data/contact_matrix/contact_matrix_fips_MN.json
  pyseir_data/contact_matrix/contact_matrix_fips_MO.json
  pyseir_data/contact_matrix/contact_matrix_fips_MS.json
  pyseir_data/contact_matrix/contact_matrix_fips_MT.json
  pyseir_data/contact_matrix/contact_matrix_fips_NC.json
  pyseir_data/contact_matrix/contact_matrix_fips_ND.json
  pyseir_data/contact_matrix/contact_matrix_fips_NE.json
  pyseir_data/contact_matrix/contact_matrix_fips_NH.json
  pyseir_data/contact_matrix/contact_matrix_fips_NJ.json
  pyseir_data/contact_matrix/contact_matrix_fips_NM.json
  pyseir_data/contact_matrix/contact_matrix_fips_NV.json
  pyseir_data/contact_matrix/contact_matrix_fips_NY.json
  pyseir_data/contact_matrix/contact_matrix_fips_OH.json
  pyseir_data/contact_matrix/contact_matrix_fips_OK.json
  pyseir_data/contact_matrix/contact_matrix_fips_OR.json
  pyseir_data/contact_matrix/contact_matrix_fips_PA.json
  pyseir_data/contact_matrix/contact_matrix_fips_RI.json
  pyseir_data/contact_matrix/contact_matrix_fips_SC.json
  pyseir_data/contact_matrix/contact_matrix_fips_SD.json
  pyseir_data/contact_matrix/contact_matrix_fips_TN.json
  pyseir_data/contact_matrix/contact_matrix_fips_TX.json
  pyseir_data/contact_matrix/contact_matrix_fips_UT.json
  pyseir_data/contact_matrix/contact_matrix_fips_VA.json
  pyseir_data/contact_matrix/contact_matrix_fips_VT.json
  pyseir_data/contact_matrix/contact_matrix_fips_WA.json
  pyseir_data/contact_matrix/contact_matrix_fips_WI.json
  pyseir_data/contact_matrix/contact_matrix_fips_WV.json
  pyseir_data/contact_matrix/contact_matrix_fips_WY.json
Labels: Modeling

#332 Pin pylint (not just the pytest plugin for it)
  pyseir/inference/infer_rt.py
  requirements_test.txt
Labels: Bug
